In [1]:
import numpy as np

In [2]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [3]:
#get shape of the matrix
data.shape

(5, 3)

In [4]:
#find the average age of students
np.mean(data[:,0])

np.float64(18.4)

In [5]:
print("Maths marks of all students are ")
data[:,1]

Maths marks of all students are 


array([85, 92, 76, 65, 90])

In [6]:
#find the highest science marks 

print("Science max is")
np.max(data[:,2])

Science max is


np.int64(95)

In [7]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [8]:
#Increase Math marks of all students by 5.
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [9]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [10]:
#Calculate the average marks in each subject (column-wise mean). 
np.sum(data,axis=0)/3

array([ 30.66666667, 144.33333333, 138.66666667])

In [11]:
#Get data of students who scored at least 80 in both subjects. 
data[(data[:,1]>80) & (data[:,2]>80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [12]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] =0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])